Adding using-pass.py in loops directory
inspirezonetech/TeachMePythonLikeIm5 pull request #112
Opened 2021-10-30 06:24 UTC by deepu14d

## for i in [1, 2, 3]:
         pass
In above example we won't get any error as we are using pass but if we don't use pass and just use for loop without body then we'll get an error. 

### 1. This pull request resolves #105 

### 2. Description 
Creating using-pass.py file inside loops directory. The files content give us introduction to pass statement with an example.  

### 3. Fill in checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [x] My code is formatted using required linting
- [x] I've run my code locally and checked it works

2021-10-30 07:48 UTC, deepu14d commented
Can you please also add the hacktoberfest label to this? 

> ### 1. This pull request resolves #105
> ### 2. Description
> Creating using-pass.py file inside loops directory. The files content give us introduction to pass statement with an example.
> 
> ### 3. Fill in checklist by marking [x]
> * [x]  I've read the CONTRIBUTING.md
> * [x]  I was assigned to this issue
> * [x]  My code is formatted using required linting
> * [x]  I've run my code locally and checked it works

2021-10-30 13:34 UTC, sabderemane requested changes
Thanks @deepu14d , I have suggested changes.

2021-10-30 13:34 UTC, sabderemane commented on loops/using-pass.py
> +# Challenge: Create a function that asks user whether he/she uses github or not, if no then print the steps to make github account
I don't understand the challenge, what do you mean ? It sounds complicated for me.

Plus, you are asking the user to create a function and the user has not seen function yet.

2021-10-30 15:52 UTC, deepu14d commented
> Thanks @deepu14d , I have suggested changes.

Oh sorry
It seem confusing to me too at first. 
Can you please help in adding a challenge? I am unable to come with something good n easy (and I am travelling, don't have access to PC. Sorry) I'll try to change challenge ASAP.

2021-10-30 20:08 UTC, sabderemane reviewed
I have made a suggestion @deepu14d , tell me what you think

2021-10-30 20:08 UTC, sabderemane commented on loops/using-pass.py
> +# Then call that function exactly 3 times using a for loop.
```suggestion
# Challenge: Create a loop with fruits and number, if it's a fruit print it, and if it's a number pass it.
# note : use typeof to make the condition
```

2021-10-31 04:53 UTC, deepu14d commented
> I have made a suggestion @deepu14d , tell me what you think

Yeah yeah it's fine, better than mine challenge. 
Thanks

2021-10-31 10:42 UTC, sabderemane approved these changes

2021-10-31 10:43 UTC, sabderemane commented
Thank you for your contribution @deepu14d 🎉

2021-10-31 10:43 UTC, merged