Create pow.py
inspirezonetech/TeachMePythonLikeIm5 pull request #125
Opened 2022-10-05 18:14 UTC by HenokB

## Please fill in this pull request template before submitting 

### 1. This pull request resolves #???
(^Fill in the issue number after #)

### 2. Description
(Write description of your changes here)

### 3. Fill in checklist by marking [x]

- [ ] I've read the CONTRIBUTING.md
- [ ] I was assigned to this issue
- [ ] My code is formatted using required linting
- [ ] I've run my code locally and checked it works

2022-10-06 20:03 UTC, sabderemane requested changes
Thank you @HenokB for your contribution 😄 There are few suggestions suggested to improve the tutorial. There are also some errors from the linter you can see [here](https://github.com/inspirezonetech/TeachMePythonLikeIm5/pull/125/checks). Don't hesite to read the [CONTRIBUTING](https://github.com/inspirezonetech/TeachMePythonLikeIm5/blob/main/CONTRIBUTING.md#use-flake8-linting-to-ensure-format-of-code-is-consistent-with-repo) guide to fix those issues.

2022-10-06 20:03 UTC, sabderemane commented on common-built-in-functions/pow.py
> +#The two-argument form pow(base, exp) is equivalent to using the power operator: base**exp.
```suggestion
# Pow is a function which takes 2 arguments (numbers) : base and exp. There is also an optional parameter called mod.
# It return base to the power exp; if the parameter mod is present, it return base to the power exp, modulo mod (computed more efficiently than pow(base, exp) % mod). 
# The two-argument form pow(base, exp) is equivalent to using the power operator: base**exp.
```

2022-10-06 20:09 UTC, HenokB commented
Thanks and I've applied all your suggestions.

2022-10-10 23:08 UTC, sabderemane reviewed
It's missing only the linter errors and after that it will be okay

2022-10-21 21:49 UTC, HenokB commented
> linter
what kind of linter?

2022-10-23 09:44 UTC, sabderemane commented
The flake8 linter, one of the check failing
You can see [here](https://github.com/inspirezonetech/TeachMePythonLikeIm5/pull/125/checks). Don't hesitate to read the [CONTRIBUTING](https://github.com/inspirezonetech/TeachMePythonLikeIm5/blob/main/CONTRIBUTING.md#use-flake8-linting-to-ensure-format-of-code-is-consistent-with-repo) guide to fix those issues.

2022-10-31 11:32 UTC, sabderemane commented
@HenokB any news on that ?

2022-10-31 15:11 UTC, funbeedev commented
@sabderemane I'll add the hacktoberfest-accepted label for now.
@HenokB We'd appreciate if you made the requested changes soon :)

2023-10-04 12:51 UTC, closed without merging